version: "3.0"

services:
  library:
    image: turbosrc-offchain-service:latest
    restart: always
    depends_on:
      - db
    ports:
      - 4002:4002
    expose:
      - "4002"
    env_file:
      - service.env
    build: ./
    tty: true

  db:
    image: postgres:13.7-bullseye
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: privatestore
    volumes:
      - db-data:/db-data/

volumes:
  db-data:
